# Generated by Django 3.1.2 on 2020-10-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20201030_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
    ]
