# Generated by Django 3.1.2 on 2020-10-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20201030_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genero',
            field=models.ManyToManyField(to='noticias.Genero'),
        ),
    ]
