# Generated by Django 3.1.2 on 2020-10-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_auto_20201030_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
