# Generated by Django 3.1.2 on 2020-10-31 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_auto_20201030_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagen',
        ),
    ]
