# Generated by Django 3.1.2 on 2020-10-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_auto_20201030_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
