# Generated by Django 3.1.2 on 2020-10-31 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_auto_20201030_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
