# Generated by Django 3.1.2 on 2020-10-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0013_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='Slug'),
        ),
    ]
