# Generated by Django 3.1.2 on 2020-10-31 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0014_auto_20201030_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrejuego', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('puntuacion', models.IntegerField(default=0)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('genero', models.ManyToManyField(to='noticias.Genero')),
            ],
        ),
    ]
