# Generated by Django 3.1.2 on 2020-10-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0015_analisis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisis',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='analisis',
            name='puntuacion',
            field=models.FloatField(default=0),
        ),
    ]
