# Generated by Django 3.1.2 on 2020-10-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0016_auto_20201031_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='titulo',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
