# Generated by Django 3.1.2 on 2020-10-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0018_remove_analisis_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='puntuacion',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
