# Generated by Django 3.1.2 on 2020-10-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0020_auto_20201031_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='puntuacion',
            field=models.CharField(max_length=3, verbose_name='Nota del juego (0.1, 1.0)'),
        ),
    ]
