# Generated by Django 3.1.2 on 2020-10-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0021_auto_20201031_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Nacimiento')),
            ],
            options={
                'ordering': ['usuario', 'apellido'],
            },
        ),
    ]
