# Generated by Django 3.1.2 on 2020-11-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0023_auto_20201031_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
