# Generated by Django 3.1.2 on 2020-11-01 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0024_auto_20201031_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
