# Generated by Django 3.1.2 on 2020-11-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0026_auto_20201101_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='imagen',
            field=models.ImageField(null=True, upload_to='analisis'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to='post'),
        ),
    ]
