# Generated by Django 3.1.2 on 2020-11-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0031_categoria_foro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
