# Generated by Django 3.1.2 on 2020-11-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0032_auto_20201127_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
    ]
