# Generated by Django 3.1.2 on 2020-11-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0033_auto_20201128_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='slug',
            field=models.CharField(max_length=200, verbose_name=models.CharField(max_length=200)),
        ),
    ]
