# Generated by Django 3.1.2 on 2020-11-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0034_auto_20201128_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug'),
        ),
    ]
