# Generated by Django 3.1.2 on 2020-11-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0036_auto_20201128_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug'),
        ),
    ]
