# Generated by Django 3.1.2 on 2020-11-28 21:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0039_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Perfil',
        ),
        migrations.RemoveField(
            model_name='analisis',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
