# Generated by Django 3.1.2 on 2020-11-28 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0040_auto_20201128_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foros', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
