# Generated by Django 3.1.2 on 2020-11-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0043_perfil_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='User',
            new_name='user',
        ),
    ]
