# Generated by Django 3.1.2 on 2020-11-29 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0048_auto_20201129_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='foros', to=settings.AUTH_USER_MODEL),
        ),
    ]
