# Generated by Django 3.1.2 on 2020-11-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0051_auto_20201129_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('post', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='noticias.foro')),
            ],
        ),
    ]
