# Generated by Django 3.1.2 on 2020-11-29 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0052_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='nombre', to=settings.AUTH_USER_MODEL),
        ),
    ]
